#!/bin/bash
# One-shot installer for the waste sorter kiosk on a fresh Raspberry Pi 5
# running Raspberry Pi OS (Trixie / labwc). Run from the repo root:
#
#     git clone https://github.com/Intira-Wichitanurak/websmartbin.git
#     cd websmartbin
#     scripts/install.sh
#     sudo reboot
#
# What it does (in order):
#   1. apt installs runtime deps (node, chromium, ffmpeg, lgpio, fonts)
#   2. npm install
#   3. pip install torch + torchvision on a disk-backed TMPDIR
#   4. patches /boot/firmware/config.txt for I2S audio + UART
#   5. writes the Chromium camera/mic policy (system-wide, mandatory)
#   6. wires up the labwc autostart -> scripts/kiosk-start.sh
#
# What it does NOT do — you still need to:
#   - drop the trained model into public/best_model.pt
#   - drop voice clips into public/voice/*.mp3
#   - flash + calibrate the ESP32 firmware (esp32_sensor_sharp_ir/)
#   - wire the hardware (see esp32_sensor_sharp_ir.ino header for pinout)

set -euo pipefail

# Resolve repo root from this script's location, then move there
REPO="$(cd "$(dirname "$(readlink -f "$0")")/.." && pwd)"
cd "$REPO"

say() { printf '\n\033[1;36m▶ %s\033[0m\n' "$*"; }

# ---------------- 1. apt packages ----------------
say "apt packages (sudo)"
sudo apt-get update
sudo apt-get install -y \
  nodejs npm \
  chromium fonts-noto-color-emoji \
  ffmpeg libavcodec-extra \
  python3-lgpio python3-flask python3-pil

# ---------------- 2. npm packages ----------------
say "npm install"
npm install

# ---------------- 3. python: torch + torchvision ----------------
# /tmp is tmpfs (2GB on Pi 5) — too small for torch. Force pip onto disk.
say "pip install torch torchvision"
if ! python3 -c "import torch, torchvision" 2>/dev/null; then
  mkdir -p /var/tmp/pipbuild
  TMPDIR=/var/tmp pip install torch torchvision --break-system-packages --no-cache-dir
else
  echo "torch + torchvision already installed — skipping"
fi

# ---------------- 4. /boot/firmware/config.txt ----------------
say "patching /boot/firmware/config.txt (I2S, UART, MAX98357A)"
CFG=/boot/firmware/config.txt

# turn off the old DAC overlay if present
sudo sed -i 's|^dtoverlay=hifiberry-dac$|#dtoverlay=hifiberry-dac|' "$CFG"
sudo sed -i 's|^dtoverlay=googlevoicehat-soundcard$|#dtoverlay=googlevoicehat-soundcard|' "$CFG"

# add what we need (only if not already there)
add_line() {
  grep -qxF "$1" "$CFG" || echo "$1" | sudo tee -a "$CFG" >/dev/null
}
add_line 'dtparam=i2s=on'
add_line 'dtoverlay=max98357a,sdmode-pin=4'
add_line 'enable_uart=1'

# ---------------- 5. Chromium policy (system-wide) ----------------
say "Chromium media policy"
sudo mkdir -p /etc/chromium/policies/managed
sudo cp scripts/chromium-camera-policy.json /etc/chromium/policies/managed/camera.json

# ---------------- 6. labwc autostart ----------------
say "labwc autostart -> scripts/kiosk-start.sh"
mkdir -p "$HOME/.config/labwc"
cat > "$HOME/.config/labwc/autostart" <<EOF
#!/bin/sh
# Auto-generated by websmartbin/scripts/install.sh
"$REPO/scripts/kiosk-start.sh" &
EOF
chmod +x "$HOME/.config/labwc/autostart"
chmod +x "$REPO/scripts/kiosk-start.sh"

# ---------------- done ----------------
cat <<EOF

✅  Install finished.

Next steps before rebooting:
  - copy your trained model to     $REPO/public/best_model.pt
  - copy voice clips into          $REPO/public/voice/*.mp3
  - flash the ESP32 firmware       $REPO/esp32_sensor_sharp_ir/
    and re-calibrate HX711         (CALIBRATION_FACTOR + BASELINE)
  - wire the hardware              (pinout in the .ino header comment)

Then:  sudo reboot

Kiosk should come up fullscreen on the next boot.
Log file:  $REPO/kiosk.log
EOF
