#!/bin/bash
# One-shot installer for the waste sorter kiosk on a fresh Raspberry Pi 5
# running Raspberry Pi OS (Trixie / labwc). Run from the repo root:
#
#     git clone https://github.com/Intira-Wichitanurak/websmartbin.git
#     cd websmartbin
#     scripts/install.sh
#     sudo reboot
#
# What it does (in order):
#   1. apt installs runtime deps (node, firefox, ffmpeg, v4l-utils, lgpio, fonts)
#   2. npm install
#   3. pip install the model backend on a disk-backed TMPDIR
#        default            tensorflow  (for the .keras model in public/)
#        WITH_TORCH=1       + torch + torchvision  (only for .pt/.pth models)
#        WITH_ONNX=1        + onnxruntime          (only for .onnx models)
#   4. patches /boot/firmware/config.txt for I2S audio + UART
#   5. writes the Firefox camera/autoplay policy (system-wide, mandatory)
#   6. wires up the labwc autostart -> scripts/kiosk-start.sh
#
# What it does NOT do — you still need to:
#   - drop the trained model into public/ and point MODEL_PATH in model_server.py at it
#   - drop voice clips into public/voice/*.mp3
#   - turn the Pi into the WiFi AP the ESP32s join:  sudo bash scripts/setup-ap.sh
#   - flash + calibrate the ESP32 firmware (esp32_node1_sensor / node2 / node3)
#   - wire the hardware (pinout is in each .ino header comment)

set -euo pipefail

# Resolve repo root from this script's location, then move there
REPO="$(cd "$(dirname "$(readlink -f "$0")")/.." && pwd)"
cd "$REPO"

say() { printf '\n\033[1;36m▶ %s\033[0m\n' "$*"; }

# ---------------- 1. apt packages ----------------
say "apt packages (sudo)"
sudo apt-get update
sudo apt-get install -y \
  nodejs npm \
  firefox fonts-noto-color-emoji \
  ffmpeg libavcodec-extra \
  v4l-utils \
  python3-lgpio python3-flask python3-pil

# ---------------- 2. npm packages ----------------
say "npm install"
npm install

# ---------------- 3. python: model backend ----------------
# model_server.py picks its backend from the model file's extension. The model
# shipped in public/ is .keras, so tensorflow is all that's needed by default —
# torch is a ~1.5GB install and only pays off if you switch back to a .pt model.
# /tmp is tmpfs (2GB on Pi 5) and too small for these wheels — force pip to disk.
mkdir -p /var/tmp/pipbuild
pip_install() {   # $1 = import name, $2.. = pip packages
  local mod="$1"; shift
  if python3 -c "import $mod" 2>/dev/null; then
    echo "$mod already installed — skipping"
  else
    TMPDIR=/var/tmp pip install "$@" --break-system-packages --no-cache-dir
  fi
}

say "pip install tensorflow (Keras 3 backend)"
pip_install tensorflow tensorflow

if [[ "${WITH_TORCH:-0}" != "0" ]]; then
  say "pip install torch torchvision (WITH_TORCH=1)"
  pip_install torch torch torchvision
fi

if [[ "${WITH_ONNX:-0}" != "0" ]]; then
  say "pip install onnxruntime (WITH_ONNX=1)"
  pip_install onnxruntime onnxruntime
fi

# ---------------- 4. /boot/firmware/config.txt ----------------
say "patching /boot/firmware/config.txt (I2S, UART, MAX98357A)"
CFG=/boot/firmware/config.txt

# turn off the old DAC overlay if present
sudo sed -i 's|^dtoverlay=hifiberry-dac$|#dtoverlay=hifiberry-dac|' "$CFG"
sudo sed -i 's|^dtoverlay=googlevoicehat-soundcard$|#dtoverlay=googlevoicehat-soundcard|' "$CFG"

# add what we need (only if not already there)
add_line() {
  grep -qxF "$1" "$CFG" || echo "$1" | sudo tee -a "$CFG" >/dev/null
}
add_line 'dtparam=i2s=on'
add_line 'dtoverlay=max98357a,sdmode-pin=4'
add_line 'enable_uart=1'

# ---------------- 5. Firefox policy (system-wide) ----------------
say "Firefox media policy (camera + autoplay)"
sudo mkdir -p /etc/firefox/policies
sudo cp scripts/firefox-policies.json /etc/firefox/policies/policies.json

# ---------------- 6. labwc autostart ----------------
say "labwc autostart -> scripts/kiosk-start.sh"
mkdir -p "$HOME/.config/labwc"
cat > "$HOME/.config/labwc/autostart" <<EOF
#!/bin/sh
# Auto-generated by websmartbin/scripts/install.sh
"$REPO/scripts/kiosk-start.sh" &
EOF
chmod +x "$HOME/.config/labwc/autostart"
chmod +x "$REPO/scripts/kiosk-start.sh"

# ---------------- done ----------------
cat <<EOF

✅  Install finished.

Next steps before rebooting:
  - copy your trained model to     $REPO/public/  (then set MODEL_PATH in model_server.py)
  - copy voice clips into          $REPO/public/voice/*.mp3
  - turn this Pi into the AP       sudo bash $REPO/scripts/setup-ap.sh
  - flash the ESP32 firmware       $REPO/esp32_node1_sensor/ (+ node2, node3)
    and re-calibrate HX711         (CALIBRATION_FACTOR + BASELINE in node #1)
  - wire the hardware              (pinout in each .ino header comment)

Then:  sudo reboot

Kiosk should come up fullscreen on the next boot.
Log file:  $REPO/kiosk.log
EOF
